export const universities = [
  { id: 'helsinki', name: 'Helsingin yliopisto' },
  { id: 'aalto', name: 'Aalto-yliopisto' },
  { id: 'turku', name: 'Turun yliopisto' },
  { id: 'tampere', name: 'Tampereen yliopisto' },
  { id: 'jyvaskyla', name: 'Jyväskylän yliopisto' },
  { id: 'oulu', name: 'Oulun yliopisto' },
  { id: 'uef', name: 'Itä-Suomen yliopisto' },
  { id: 'lapland', name: 'Lapin yliopisto' },
  { id: 'lut', name: 'LUT-yliopisto' },
  { id: 'vaasa', name: 'Vaasan yliopisto' },
  { id: 'hanken', name: 'Hanken Svenska handelshögskolan' },
  { id: 'uniarts', name: 'Taideyliopisto' },
];

export const uas = [
  { id: 'haaga-helia', name: 'Haaga-Helia ammattikorkeakoulu' },
  { id: 'metropolia', name: 'Metropolia Ammattikorkeakoulu' },
  { id: 'laurea', name: 'Laurea-ammattikorkeakoulu' },
  { id: 'tamk', name: 'Tampereen ammattikorkeakoulu' },
  { id: 'turku-amk', name: 'Turun ammattikorkeakoulu' },
  { id: 'oamk', name: 'Oulun ammattikorkeakoulu' },
  { id: 'jamk', name: 'Jyväskylän ammattikorkeakoulu' },
  { id: 'xamk', name: 'Kaakkois-Suomen ammattikorkeakoulu' },
  { id: 'novia', name: 'Yrkeshögskolan Novia' },
  { id: 'arcada', name: 'Yrkeshögskolan Arcada' },
  { id: 'samk', name: 'Satakunnan ammattikorkeakoulu' },
  { id: 'seamk', name: 'Seinäjoen ammattikorkeakoulu' },
  { id: 'savonia', name: 'Savonia-ammattikorkeakoulu' },
  { id: 'karelia', name: 'Karelia-ammattikorkeakoulu' },
  { id: 'lapinamk', name: 'Lapin ammattikorkeakoulu' },
  { id: 'kamk', name: 'Kajaanin ammattikorkeakoulu' },
  { id: 'vamk', name: 'Vaasan ammattikorkeakoulu' },
  { id: 'centria', name: 'Centria-ammattikorkeakoulu' },
  { id: 'diak', name: 'Diakonia-ammattikorkeakoulu' },
  { id: 'humak', name: 'Humanistinen ammattikorkeakoulu' },
];
